import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import BGMProvider from './BGMProvider';
import SiteLockProvider from './SiteLockProvider'; // Import the new provider

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BGMProvider>
          <SiteLockProvider>
            {children}
          </SiteLockProvider>
        </BGMProvider>
      </body>
    </html>
  );
}
